
export enum Shape {
  TRIANGLE = 3,
  SQUARE,
  PENTAGONE,
  HEXAGONE,
  HEPTAGONE,
  OCTAGONE,
  NONAGONE,
  DECAGONE,
  HANDECAGONE,
  DODECAGONE
}

export interface ShapeConstants {
  MULTIPLICATEUR_X: number;
  MULTIPLICATEURY: number;
  DECALAGE_X: number;
  DECALAGE_Y: number;
  RATIO_TRANSITION_WIDTH: number;
  FACTEUR_TRANSITION: number;
  FACTEUR_DECALAGE_X: number;
  FACTEUR_DECALAGE_Y: number;
  FACTEUR_BORDER_X: number;
  FACTEUR_BORDER_Y: number;
}

export const CONSTANTS: Map<Shape, ShapeConstants> = new Map ([
  [Shape.TRIANGLE, {
    MULTIPLICATEUR_X: 1.15,
    MULTIPLICATEURY: 1.32,
    DECALAGE_X: 1.15,
    DECALAGE_Y: 0.88,

    RATIO_TRANSITION_WIDTH: 1.15,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.8,
    FACTEUR_BORDER_Y: 2.0
  }],
  [Shape.SQUARE, {
    MULTIPLICATEUR_X: 1.0,
    MULTIPLICATEURY: 1.0,
    DECALAGE_X: 1.0,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.0,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.38,
    FACTEUR_BORDER_Y: 1.38,
  }],
  [Shape.PENTAGONE, {
    MULTIPLICATEUR_X: 1.05,
    MULTIPLICATEURY: 1.1,
    DECALAGE_X: 1.05,
    DECALAGE_Y: 0.97,
    RATIO_TRANSITION_WIDTH: 1.04,
    FACTEUR_TRANSITION: 1.01,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.2,
    FACTEUR_BORDER_Y: 1.2,
  }],
  [Shape.HEXAGONE, {
    MULTIPLICATEUR_X: 1.1,
    MULTIPLICATEURY: 1.0,
    DECALAGE_X: 0.9,
    DECALAGE_Y: 1.1,
    RATIO_TRANSITION_WIDTH: 1.1,
    FACTEUR_TRANSITION: 0.909,
    FACTEUR_DECALAGE_X: 0.9,
    FACTEUR_DECALAGE_Y: 0.92,
    FACTEUR_BORDER_X: 1.0,
    FACTEUR_BORDER_Y: 1.0,
  }],
  [Shape.HEPTAGONE, {
    MULTIPLICATEUR_X: 1.015,
    MULTIPLICATEURY: 1.05,
    DECALAGE_X: 1.025,
    DECALAGE_Y: 1.08,
    RATIO_TRANSITION_WIDTH: 1.1,
    FACTEUR_TRANSITION: 1.02,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.0,
    FACTEUR_BORDER_Y: 1.0,
  }],
  [Shape.OCTAGONE, {
    MULTIPLICATEUR_X: 1.0,
    MULTIPLICATEURY: 1.0,
    DECALAGE_X: 1.0,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.0,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.1,
    FACTEUR_BORDER_Y: 1.1,
  }],
  [Shape.NONAGONE, {
    MULTIPLICATEUR_X: 1.01,
    MULTIPLICATEURY: 1.027,
    DECALAGE_X: 1.0,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.04,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.05,
    FACTEUR_BORDER_Y: 1.05,
  }],
  [Shape.DECAGONE, {
    MULTIPLICATEUR_X: 1.0,
    MULTIPLICATEURY: 1.0,
    DECALAGE_X: 1.0,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.06,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 0.95,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.0,
    FACTEUR_BORDER_Y: 1.0,
  }],
  [Shape.HANDECAGONE, {
    MULTIPLICATEUR_X: 1.01,
    MULTIPLICATEURY: 1.02,
    DECALAGE_X: 1.02,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.08,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.3,
    FACTEUR_BORDER_Y: 1.03,
  }],
  [Shape.DODECAGONE, {
    MULTIPLICATEUR_X: 1.0,
    MULTIPLICATEURY: 1.0,
    DECALAGE_X: 1.0,
    DECALAGE_Y: 1.0,
    RATIO_TRANSITION_WIDTH: 1.0,
    FACTEUR_TRANSITION: 1.0,
    FACTEUR_DECALAGE_X: 1.0,
    FACTEUR_DECALAGE_Y: 1.0,
    FACTEUR_BORDER_X: 1.01,
    FACTEUR_BORDER_Y: 1.01,
  }],
]);
